// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZfyGSBYgsbe5z0napHO2HQBsNERjLz6A',
    appId: '1:472741962249:web:8f6b0200a64578607a0ed8',
    messagingSenderId: '472741962249',
    projectId: 'seniordesign-99fb8',
    authDomain: 'seniordesign-99fb8.firebaseapp.com',
    storageBucket: 'seniordesign-99fb8.appspot.com',
    measurementId: 'G-TQQE4EQPGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoO5RL7cslYwoIfxgMrWKA2_dOprMzVD4',
    appId: '1:472741962249:android:84a74febf78a83407a0ed8',
    messagingSenderId: '472741962249',
    projectId: 'seniordesign-99fb8',
    storageBucket: 'seniordesign-99fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBlyN6iL1Z-7cwKGk9WIqP9Hd4WNcm4HA',
    appId: '1:472741962249:ios:3736b8ec1fb0b2107a0ed8',
    messagingSenderId: '472741962249',
    projectId: 'seniordesign-99fb8',
    storageBucket: 'seniordesign-99fb8.appspot.com',
    iosClientId:
        '472741962249-e7b0eo2ccg8blbqr8k3ns4m1r8ju9c0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.twige',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBlyN6iL1Z-7cwKGk9WIqP9Hd4WNcm4HA',
    appId: '1:472741962249:ios:3736b8ec1fb0b2107a0ed8',
    messagingSenderId: '472741962249',
    projectId: 'seniordesign-99fb8',
    storageBucket: 'seniordesign-99fb8.appspot.com',
    iosClientId:
        '472741962249-e7b0eo2ccg8blbqr8k3ns4m1r8ju9c0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.twige',
  );
}
